version: '3'

services:
  #Redis
  redis:
    image: "redis:latest"
    ports:
      - "16379:6379"
    volumes:
      - "./data/redis:/data"

  #RedisInsight
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 18001:8001
    volumes:
      - ./data/redisinsight:/db

  #MySQL
  mysql:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: beyondz_db
      MYSQL_USER: beyondz_user
      MYSQL_PASSWORD: beyondz_pass
      TZ: 'Asia/Tokyo'
    volumes:
     - ./data/mysql:/var/lib/mysql

  #Adminer
  adminer:
    image: adminer
    restart: always
    ports:
      - 18080:8080
    volumes:
     - ./data/adminer:/var/lib/mysql
