version: '3'

services:
  #Redis
  redis:
    image: "redis:latest"
    ports:
      - "16379:6379"
    volumes:
      - "./data/redis:/data"

  #RedisInsight
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 18001:8001
    volumes:
      - ./data/redisinsight:/db
